### ISSUE TITLE
장기간 돌렸을때 오차 누적으로 인해 바퀴가 로봇 외부로 나와버리는 Issue

### ISSUE THREAD

**Issue by chshong** [aiwc/test_world#2]
바퀴가 움직이기는 함

**Comment by ibjeong** [comment]
3.5일 정도 돌리면 눈에 띄게 오차가 보이는 듯? 로봇 위치만 초기화하는게 아니라 아예 새 노드를 만들어서 넣는 것으로 변경해야 할 것 같아요.

**Comment by chshong** [comment]
해결된 듯 합니다.
